### ISSUE TITLE
Error expected EOI or IP

### ISSUE THREAD

**Issue by whydn-dev** [bebasid/bebasin#10]
![image](https://user-images.githubusercontent.com/50127599/85850803-b920af00-b7d7-11ea-8693-bb57cddc99e1.png)

**Comment by andraantariksa** [comment]
Buka file di `C:\Windows\System32\drivers\etc\hosts` dan `C:\Windows\System32\drivers\etc\hosts-backup` dengan notepad, copy isinya kesini

**Comment by whydn-dev** [comment]
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
192.168.1.15 host.docker.internal
192.168.1.15 gateway.docker.internal
169.254.214.67 host.docker.internal
169.254.214.67 gateway.docker.internal
192.168.1.19 host.docker.internal
192.168.1.19 gateway.docker.internal
192.168.1.7 host.docker.internal
192.168.1.7 gateway.docker.internal
192.168.1.14 host.docker.internal
192.168.1.14 gateway.docker.internal
192.168.1.17 host.docker.internal
192.168.1.17 gateway.docker.internal
192.168.137.249 host.docker.internal
192.168.137.249 gateway.docker.internal
10.10.17.104 host.docker.internal
10.10.17.104 gateway.docker.internal
10.10.16.128 host.docker.internal
10.10.16.128 gateway.docker.internal
10.10.15.192 host.docker.internal
10.10.15.192 gateway.docker.internal
10.10.15.191 host.docker.internal
10.10.15.191 gateway.docker.internal
10.70.53.4 host.docker.internal
10.70.53.4 gateway.docker.internal
192.168.137.6 host.docker.internal
192.168.137.6 gateway.docker.internal
10.5.11.134 host.docker.internal
10.5.11.134 gateway.docker.internal
10.5.10.128 host.docker.internal
10.5.10.128 gateway.docker.internal
192.168.43.113 host.docker.internal
192.168.43.113 gateway.docker.internal
192.168.1.4 host.docker.internal
192.168.1.4 gateway.docker.internal
10.70.157.157 host.docker.internal
10.70.157.157 gateway.docker.internal
10.96.172.3 host.docker.internal
10.96.172.3 gateway.docker.internal
10.5.10.150 host.docker.internal
10.5.10.150 gateway.docker.internal
192.168.1.3 host.docker.internal
192.168.1.3 gateway.docker.internal
192.168.31.249 host.docker.internal
192.168.31.249 gateway.docker.internal
169.254.26.229 host.docker.internal
169.254.26.229 gateway.docker.internal
192.168.31.128 host.docker.internal
192.168.31.128 gateway.docker.internal
192.168.31.117 host.docker.internal
192.168.31.117 gateway.docker.internal
192.168.31.97 host.docker.internal
192.168.31.97 gateway.docker.internal
172.20.10.6 host.docker.internal
172.20.10.6 gateway.docker.internal
172.20.10.3 host.docker.internal
172.20.10.3 gateway.docker.internal
172.20.10.2 host.docker.internal
172.20.10.2 gateway.docker.internal
 host.docker.internal
 gateway.docker.internal
# Added by Docker Desktop
172.20.10.4 host.docker.internal
172.20.10.4 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section


Untuk file hosts-backup tidak terbuat

**Comment by andraantariksa** [comment]
Di bagian ini mestinya nggak boleh ada newline

```
172.20.10.2 gateway.docker.internal
 host.docker.internal
 gateway.docker.internal
```

Seharusnya jadi seperti ini

```
172.20.10.2 gateway.docker.internal host.docker.internal gateway.docker.internal
```

---

Hostsnya silahkan diganti dengan ini

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
192.168.1.15 host.docker.internal
192.168.1.15 gateway.docker.internal
169.254.214.67 host.docker.internal
169.254.214.67 gateway.docker.internal
192.168.1.19 host.docker.internal
192.168.1.19 gateway.docker.internal
192.168.1.7 host.docker.internal
192.168.1.7 gateway.docker.internal
192.168.1.14 host.docker.internal
192.168.1.14 gateway.docker.internal
192.168.1.17 host.docker.internal
192.168.1.17 gateway.docker.internal
192.168.137.249 host.docker.internal
192.168.137.249 gateway.docker.internal
10.10.17.104 host.docker.internal
10.10.17.104 gateway.docker.internal
10.10.16.128 host.docker.internal
10.10.16.128 gateway.docker.internal
10.10.15.192 host.docker.internal
10.10.15.192 gateway.docker.internal
10.10.15.191 host.docker.internal
10.10.15.191 gateway.docker.internal
10.70.53.4 host.docker.internal
10.70.53.4 gateway.docker.internal
192.168.137.6 host.docker.internal
192.168.137.6 gateway.docker.internal
10.5.11.134 host.docker.internal
10.5.11.134 gateway.docker.internal
10.5.10.128 host.docker.internal
10.5.10.128 gateway.docker.internal
192.168.43.113 host.docker.internal
192.168.43.113 gateway.docker.internal
192.168.1.4 host.docker.internal
192.168.1.4 gateway.docker.internal
10.70.157.157 host.docker.internal
10.70.157.157 gateway.docker.internal
10.96.172.3 host.docker.internal
10.96.172.3 gateway.docker.internal
10.5.10.150 host.docker.internal
10.5.10.150 gateway.docker.internal
192.168.1.3 host.docker.internal
192.168.1.3 gateway.docker.internal
192.168.31.249 host.docker.internal
192.168.31.249 gateway.docker.internal
169.254.26.229 host.docker.internal
169.254.26.229 gateway.docker.internal
192.168.31.128 host.docker.internal
192.168.31.128 gateway.docker.internal
192.168.31.117 host.docker.internal
192.168.31.117 gateway.docker.internal
192.168.31.97 host.docker.internal
192.168.31.97 gateway.docker.internal
172.20.10.6 host.docker.internal
172.20.10.6 gateway.docker.internal
172.20.10.3 host.docker.internal
172.20.10.3 gateway.docker.internal
172.20.10.2 host.docker.internal
172.20.10.2 gateway.docker.internal host.docker.internal gateway.docker.internal
# Added by Docker Desktop
172.20.10.4 host.docker.internal
172.20.10.4 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by nxzlem** [comment]
halo kak (@whydn-dev), anda sudah bisa memperbaiki hostsnya? tolong respon ya, terima kasih

**Comment by whydn-dev** [comment]
Apakah di running tanpa admin permission menjadi masalah ?

**Comment by andraantariksa** [comment]
Kalo dirun tanpa admin permission akan ada error message `no priviledges`, `OS error` atau semacamnya. Udah coba yang sama minta (https://github.com/bebasid/bebasin/issues/10#issuecomment-650532442) ?

**Comment by whydn-dev** [comment]
Ok mungkin ada masalah dari config hostnya,
