### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ryndrx** [bebasid/bebasin#11]
![22](https://user-images.githubusercontent.com/67512156/85925418-87384700-b8c2-11ea-9fcb-41565a7c6602.PNG)
itu kenapa ya min? padahal udah diupdate sama udah dijalanin pake run as administrator

**Comment by andraantariksa** [comment]
Buka file di `C:\Windows\System32\drivers\etc\hosts` dan `C:\Windows\System32\drivers\etc\hosts-backup` dengan notepad, copy isinya kesini

**Comment by Ryndrx** [comment]
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
# 127.0.0.1       localhost
# ::1             localhost

Pada tanggal Min, 28 Jun 2020 pukul 11.49 Andra Antariksa <
notifications@github.com> menulis:

**Comment by nxzlem** [comment]
@andraantariksa https://users.rust-lang.org/t/solved-stream-did-not-contain-valid-utf-8/10186 maaf atao salah
@Ryndrx 
itu time text encoding ada ngebug ya? 
![UbBTN1U](https://i.imgur.com/UbBTN1U.png)

**Comment by andraantariksa** [comment]
Coba file yang ada di `C:\Windows\System32\drivers\etc\hosts` dikosongin aja

**Comment by Ryndrx** [comment]
iya gan ada error itu

Pada tanggal Sab, 4 Jul 2020 pukul 12.14 NXzLEM <notifications@github.com>
menulis:

**Comment by nxzlem** [comment]
berarti ada ngebug UTF-8 encoding tuh. Coba perbaiki timestampnya situ re-open lagi.

**Comment by nxzlem** [comment]
@andraantariksa tolong bacakan disini ya, terima kasih
https://stackoverflow.com/questions/43122335/what-does-stream-did-not-contain-valid-utf-8-mean

**Comment by andraantariksa** [comment]
Coba hapus file hostsnya, terus bikin baru pake notepad. Saat disave di notepad jangan lupa set encodingnya UTF8
