### ISSUE TITLE
Update Version BUG

### ISSUE THREAD

**Issue by mozarik** [bebasid/bebasin#12]
OS : Ubuntu LTS 20.04 

Setelah saya menjalankan Update . disuruh untuk restart app nya . lalu ketika saya cek nomor versi nya belum terupadte di GUI nya atau memang app nya belum terupdate sama sekali. 

![image](https://user-images.githubusercontent.com/39885486/85928720-aabeba00-b8e1-11ea-9aa2-7b79b11e09ce.png)
![image](https://user-images.githubusercontent.com/39885486/85928733-c32ed480-b8e1-11ea-8d54-73ef19516280.png)

Setelah melakukan update dan restart app

![image](https://user-images.githubusercontent.com/39885486/85928724-b7431280-b8e1-11ea-92bc-d25f9ca3f971.png)

**Comment by andraantariksa** [comment]
Fixed

**Penyebab:**
CInya error & GitHub memang sering down
