### ISSUE TITLE
Bug pilihan Repository .

### ISSUE THREAD

**Issue by mozarik** [bebasid/bebasin#13]
OS : Ubuntu 20.04 

Ketika memilih menu "Repository" muncul prompt bahwa tidak ada browser yang bisa dibuka 

![image](https://user-images.githubusercontent.com/39885486/85928791-4c460b80-b8e2-11ea-9855-4d2b031c62e7.png)

**Comment by andraantariksa** [comment]
Ada browser yang keinstall?

**Comment by mozarik** [comment]
> Ada browser yang keinstall?

Mozilla dan Google Chrome terinstall . Default Browser Google Chrome

**Comment by andraantariksa** [comment]
Coba buat set default browser.

Kita pakai library [webbrowser](https://docs.rs/webbrowser/0.5.2/webbrowser/), dan webbrowser melakukan call ke command di bawah ini (untuk UNIX)

```
xdg-open
kioclient
gvfs-open
gnome-open
open
x-www-browser
```

Kalau tidak bisa ya mungkin ada masalah dari command di atas atau dari OSnya sendiri. Untuk Windows seharusnya tidak ada masalah karena semua Windows punya konfigurasi yang sama.

Karena ini out of concern dari Bebasin, silahkan submit issue ke https://github.com/amodm/webbrowser-rs. Issuenya saya tutup
