### ISSUE TITLE
Error : Expected EOI or IP

### ISSUE THREAD

**Issue by mozarik** [bebasid/bebasin#17]
Ada error yang saya dapat ketika melakukan instalasi 

![image](https://user-images.githubusercontent.com/39885486/87446231-9a217a00-c62b-11ea-9f40-f3d90c39040a.png)

Windows 10, 2004. 

File Hosts sudah saya kosongkan, dan app sudah dijalankan secara Admin

**Comment by andraantariksa** [comment]
Hmmm, itu sepertinya masih ada sisa 1 karakter. Barusan ngecek grammarnya juga nggak ada masalah kalo file hostsnya kosong.

Coba hapus file hostsnya kemudian dicreate lagi, jadi biar filenya bener-bener kosong

**Comment by mozarik** [comment]
sudah, masih sama seperti itu juga. 

saya udah coba 2 cara . satu yang bener bener kosong 

dan satu nya lagi saya isi default seperti ini
![image](https://user-images.githubusercontent.com/39885486/87448045-e53c8c80-c62d-11ea-917e-ea8cbf4817ca.png)

**Comment by andraantariksa** [comment]
Untuk text encodingnya apa sudah UTF-8?

**Comment by nxzlem** [comment]
itu sudah di replace gan?
