### ISSUE TITLE
Tidak bisa di update

### ISSUE THREAD

**Issue by xeniel768** [bebasid/bebasin#18]
![image](https://user-images.githubusercontent.com/53806941/89680614-7a752d00-d91d-11ea-9cfd-a2f20ecfda21.png)

udh di cba Run Admin tetep versi nya ga mau ganti

**Comment by berbahagia3** [comment]
saya juga mengalami hal yg sama, semenjak Bebasin Version 202008311635 tidak bisa update.
Sudah coba Run Admin lalu pas click update muncul konfirmasi utk update ke versi 202009130437 namun setelah selesai update versi tetap 202008311635

**Comment by nxzlem** [comment]
Halo, @xeniel768 
Code Error 2 itu tidak ada file hosts nya, tolong anda di tambahkan hosts nya lewat create a new text, terus di gantikan jadi "hosts" saja. Jangan di kasi format apapun, gitu saja.
Terus teks itu tidak perlu isi apapun jadi biarkan saja kayak gitu. Terus buka lagi bebasin nya dan install hosts nya.
atau baca dari sini.
