### ISSUE TITLE
error code (os error 2)

### ISSUE THREAD

**Issue by AriefLamzi** [bebasid/bebasin#22]
![err](https://user-images.githubusercontent.com/78098526/106022222-2f7fe980-60f8-11eb-841d-e340af9aeab5.png)

Yang di client gui bebasid juga ngga mau buka walaupun sudah di run as admin.

**Comment by nxzlem** [comment]
Halo, @AriefLamzi  
Code Error 2 itu tidak ada file hosts nya, tolong anda di tambahkan hosts nya lewat create a new text, terus di gantikan jadi "hosts" saja. Jangan di kasi format apapun, gitu saja.
Terus teks itu tidak perlu isi apapun jadi biarkan saja kayak gitu. Terus buka lagi bebasin nya dan install hosts nya.
atau baca dari sini.
