### ISSUE TITLE
The System cannot find the file specified. ( os error 2 )

### ISSUE THREAD

**Issue by ahniki** [bebasid/bebasin#23]
![image_2021-02-05_145904](https://user-images.githubusercontent.com/78587731/107005708-b13fd900-67c2-11eb-8392-74135cbb3a62.png)

**Comment by nxzlem** [comment]
Halo, @ahniki  
Code Error 2 itu tidak ada file hosts nya, tolong anda di tambahkan hosts nya lewat create a new text, terus di gantikan jadi "hosts" saja. Jangan di kasi format apapun, gitu saja.
Terus teks itu tidak perlu isi apapun jadi biarkan saja kayak gitu. Terus buka lagi bebasin nya dan install hosts nya.
atau baca dari sini.
