### ISSUE TITLE
gagal install dan membuka file bebasid .exe

### ISSUE THREAD

**Issue by ramangan21** [bebasid/bebasin#24]
saat membuka bebasin mendapatkan error the system cannot find the file specified. (os error 2).

saat membuka bebasid.exe tidak bisa terbuka walau sudah run as administrator

![image](https://user-images.githubusercontent.com/78688280/107147196-53a4bb80-697f-11eb-8eae-83914d2c91a0.png)

**Comment by nxzlem** [comment]
Halo, @ramangan21 
Code Error 2 itu tidak ada file hosts nya, tolong anda di tambahkan hosts nya lewat create a new text, terus di gantikan jadi "hosts" saja. Jangan di kasi format apapun, gitu saja.
Terus teks itu tidak perlu isi apapun jadi biarkan saja kayak gitu. Terus buka lagi bebasin nya dan install hosts nya.
atau baca dari sini.
