### ISSUE TITLE
System Cannot Find The File Specifed (os error 2)

### ISSUE THREAD

**Issue by DeasPR** [bebasid/bebasin#25]
![image](https://user-images.githubusercontent.com/36984754/107775460-e1fbb180-6d72-11eb-8fcc-f8b671da37f5.png)

**Comment by nxzlem** [comment]
Halo, @DeasPR 
Code Error 2 itu tidak ada file hosts nya, tolong anda di tambahkan hosts nya lewat create a new text, terus di gantikan jadi "hosts" saja. Jangan di kasi format apapun, gitu saja.
Terus teks itu tidak perlu isi apapun jadi biarkan saja kayak gitu. Terus buka lagi bebasin nya dan install hosts nya.
atau baca dari sini.
