### ISSUE TITLE
macos

### ISSUE THREAD

**Issue by muhammadidan** [bebasid/bebasin#3]
gan ada tutorial pake di mac os ga?

**Comment by andraantariksa** [comment]
Untuk sementara belum support MacOS. Mungkin besok saya tambahin untuk MacOS

**Comment by andraantariksa** [comment]
MacOS udah disupport di commit terbaru (99b63369012b45f85da004b15a93112a5e1ad0d0). Bisa didownload di https://github.com/bebasid/bebasin/releases

Untuk sekarang CInya lagi erorr, jadi belum ada di rilis.. lagi nunggu admin organisasi buat approve. Mungkin besok (13 Mei 2020) udah ada
