### ISSUE TITLE
Habis makek ini di PC windows 10 kok gabisa

### ISSUE THREAD

**Issue by vibersays** [bebasid/bebasin#6]
kak habis makek ini di windows 10 koneksi indihome di pc , setelah itu kerestart otomatis ,nahh habis itu kok gabisa buat internet samsek yaa ,padahal di hp lancar :'(

**Comment by andraantariksa** [comment]
Buka file di `C:\Windows\System32\drivers\etc\hosts` dengan notepad, terus copy isinya kesini

**Comment by nxzlem** [comment]
@vibersays tolong jelaskan responnya ya terima kasih

**Comment by nxzlem** [comment]
@vibersays
